const Employee=require('../app/controller/employee.controller')
const { authToThisRoute, auth } = require('../app/mddleware')
const router =require('express').Router()
router.post('/lavie/employee', auth,authToThisRoute,Employee.addEmployee)
router.post('/lavie/employee/login', Employee.logIn)
router.delete('/lavie/employee/logout',auth,Employee.logOut)
router.delete('/lavie/employee/logoutFromAll',auth,Employee.logOutFromAllDevices)
router.post('/lavie/employee/phonenumber',auth,Employee.addPhoneNumberToEmployee_Me)
router.get('/lavie/confirm/employee/:confimation', auth, Employee.myProfile)
router.put('/lavie/activatesupporter/:supporter',auth,authToThisRoute,Employee.activateSupporter)
router.put('/lavie/deactivatesupporter/:supporter',auth,authToThisRoute,Employee.deactivateSupporter)
router.delete('/lavie/employee/:id',auth,authToThisRoute,Employee.deleteEmployee)
router.put('/lavie/employee',auth,Employee.editeEmployee_ME)
router.get('/lavie/employee',auth,Employee.myProfile)
router.get('/lavie/employees',auth,authToThisRoute,Employee.getEmployees)
module.exports=router