const Plant=require('../app/controller/plant.controller')
const { authToThisRoute, auth } = require('../app/mddleware')
const router=require('express').Router()
router.post('/lavie/plant',auth,authToThisRoute,Plant.add)
router.put('/lavie/plant/:id',auth,authToThisRoute,Plant.edit)
router.delete('/lavie/plant/:id',auth,authToThisRoute,Plant.delete)
router.get('/lavie/plant/:search',auth,Plant.searchAbout)
router.get('/lavie/plants',Plant.getAll)
router.get('/lavie/singleplant/:id',Plant.getSingle)
module.exports=router