const Product=require('../app/controller/products controller')
const { authToThisRoute, auth } = require('../app/mddleware')
const router=require('express').Router()
router.post('/lavie/product',auth,authToThisRoute,Product.add)
router.delete('/lavie/product/:id',auth,authToThisRoute,Product.delete)
router.put('/lavie/product/:id',auth,authToThisRoute,Product.edit)
router.get('/lavie/product',Product.getAll)
router.get('/lavie/product/:id',Product.getSingle)
router.post('/lavie/rateproduct/:id',auth,Product.rate)
router.get('/lavie/suggestedproduct',auth,authToThisRoute,Product.showSuggestedProduct)
router.get('/lavie/showproductRating/:id',Product.showProductRatings)
router.put('/lavie/blogmoreHelpful/:productID/:rateID',auth,Product.moreHelpful)
module.exports=router