const User = require('../app/controller/user.controller')
require('../app/passport')
const passport = require('passport');
const { authToThisRoute, auth } = require('../app/mddleware')
const router = require('express').Router()
// sign up
router.post('/lavia/signup', User.signUp)
router.get('/lavia/confirm/user/:confimation', auth, authToThisRoute, User.myProfile)
// login with another app
router.get('/fail', (req, res) => { res.status(500).send({ apiStatus: false, data: {}, apiMessage: 'somthing go wrong please try to log in again' }) })
router.get('/good', User.logInByApps)
// with facebook
router.get('/lavie/facebooklogin', passport.authenticate('facebook', { scope: 'email' }))
router.get('/lavie/facebooklogin/callback', passport.authenticate('facebook', { successRedirect: '/good', failureRedirect: '/fail' }))
// with google
router.get('/lavie/googlelogin', passport.authenticate('google', { scope: ['profile', 'email'] }))
router.get('/lavie/googlelogin/callback', passport.authenticate('google', { failureRedirect: '/failed' }), (req, res) => { res.redirect('/good'); })
// login with username &pass
router.post('/lavia/login', User.logIn)
// forget pass
router.post('/lavia/forgetpass', User.forgetMyPass)
router.post('/lavia/forgetpass/changepass/:token', User.resetPass)
// log Out
router.get('/lavie/logout', auth, authToThisRoute, User.logOut)
// privacy policy
router.get('/lavie/privacypolicy', User.getPrivacyPolicy)
//set my level
router.post('/lavie/setlevel', auth, authToThisRoute, User.setLevel)

router.get('/lavia/myprofile', auth, User.myProfile)

module.exports = router





// IncomingMessage {
//     _readableState: ReadableState {
//         objectMode: false,
//             highWaterMark: 16384,
//                 buffer: BufferList { head: null, tail: null, length: 0 },
//         length: 0,
//             pipes: [],
//                 flowing: null,
//                     ended: true,
//                         endEmitted: false,
//                             reading: false,
//                                 constructed: true,
//                                     sync: true,
//                                         needReadable: false,
//                                             emittedReadable: false,
//                                                 readableListening: false,
//                                                     resumeScheduled: false,
//                                                         errorEmitted: false,
//                                                             emitClose: true,
//                                                                 autoDestroy: true,
//                                                                     destroyed: false,
//                                                                         errored: null,
//                                                                             closed: false,
//                                                                                 closeEmitted: false,
//                                                                                     defaultEncoding: 'utf8',
//                                                                                         awaitDrainWriters: null,
//                                                                                             multiAwaitDrain: false,
//                                                                                                 readingMore: true,
//                                                                                                     dataEmitted: false,
//                                                                                                         decoder: null,
//                                                                                                             encoding: null,
//                                                                                                                 [Symbol(kPaused)]: null
//     },
//     _events: [Object: null prototype] { },
//     _eventsCount: 0,
//         _maxListeners: undefined,
//             socket: <ref * 1 > Socket {
//         connecting: false,
//             _hadError: false,
//                 _parent: null,
//                     _host: null,
//                         _closeAfterHandlingError: false,
//                             _readableState: ReadableState {
//             objectMode: false,
//                 highWaterMark: 16384,
//                     buffer: BufferList { head: null, tail: null, length: 0 },
//             length: 0,
//                 pipes: [],
//                     flowing: true,
//                         ended: false,
//                             endEmitted: false,
//                                 reading: true,
//                                     constructed: true,
//                                         sync: false,
//                                             needReadable: true,
//                                                 emittedReadable: false,
//                                                     readableListening: false,
//                                                         resumeScheduled: false,
//                                                             errorEmitted: false,
//                                                                 emitClose: false,
//                                                                     autoDestroy: true,
//                                                                         destroyed: false,
//                                                                             errored: null,
//                                                                                 closed: false,
//                                                                                     closeEmitted: false,
//                                                                                         defaultEncoding: 'utf8',
//                                                                                             awaitDrainWriters: null,
//                                                                                                 multiAwaitDrain: false,
//                                                                                                     readingMore: false,
//                                                                                                         dataEmitted: false,
//                                                                                                             decoder: null,
//                                                                                                                 encoding: null,
//                                                                                                                     [Symbol(kPaused)]: false
//         },
//         _events: [Object: null prototype] {
//             end: [Array],
//                 timeout: [Function: socketOnTimeout],
//                     data: [Function: bound socketOnData],
//                         error: [Function: socketOnError],
//                             close: [Array],
//                                 drain: [Function: bound socketOnDrain],
//                                     resume: [Function: onSocketResume],
//                                         pause: [Function: onSocketPause]
//         },
//         _eventsCount: 8,
//             _maxListeners: undefined,
//                 _writableState: WritableState {
//             objectMode: false,
//                 highWaterMark: 16384,
//                     finalCalled: false,
//                         needDrain: false,
//                             ending: false,
//                                 ended: false,
//                                     finished: false,
//                                         destroyed: false,
//                                             decodeStrings: false,
//                                                 defaultEncoding: 'utf8',
//                                                     length: 0,
//                                                         writing: false,
//                                                             corked: 0,
//                                                                 sync: true,
//                                                                     bufferProcessing: false,
//                                                                         onwrite: [Function: bound onwrite],
//                                                                             writecb: null,
//                                                                                 writelen: 0,
//                                                                                     afterWriteTickInfo: null,
//                                                                                         buffered: [],
//                                                                                             bufferedIndex: 0,
//                                                                                                 allBuffers: true,
//                                                                                                     allNoop: true,
//                                                                                                         pendingcb: 0,
//                                                                                                             constructed: true,
//                                                                                                                 prefinished: false,
//                                                                                                                     errorEmitted: false,
//                                                                                                                         emitClose: false,
//                                                                                                                             autoDestroy: true,
//                                                                                                                                 errored: null,
//                                                                                                                                     closed: false,
//                                                                                                                                         closeEmitted: false,
//                                                                                                                                             [Symbol(kOnFinished)]: []
//         },
//         allowHalfOpen: true,
//             _sockname: null,
//                 _pendingData: null,
//                     _pendingEncoding: '',
//                         server: Server {
//             maxHeaderSize: undefined,
//                 insecureHTTPParser: undefined,
//                     requestTimeout: 300000,
//                         headersTimeout: 60000,
//                             keepAliveTimeout: 5000,
//                                 connectionsCheckingInterval: 30000,
//                                     _events: [Object: null prototype],
//                                         _eventsCount: 2,
//                                             _maxListeners: undefined,
//                                                 _connections: 1,
//                                                     _handle: [TCP],
//                                                         _usingWorkers: false,
//                                                             _workers: [],
//                                                                 _unref: false,
//                                                                     allowHalfOpen: true,
//                                                                         pauseOnConnect: false,
//                                                                             noDelay: true,
//                                                                                 keepAlive: false,
//                                                                                     keepAliveInitialDelay: 0,
//                                                                                         httpAllowHalfOpen: false,
//                                                                                             timeout: 0,
//                                                                                                 maxHeadersCount: null,
//                                                                                                     maxRequestsPerSocket: 0,
//                                                                                                         _connectionKey: '6::::3000',
//                                                                                                             [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//                                                                                                                 [Symbol(ServerResponse)]: [Function: ServerResponse],
//                                                                                                                     [Symbol(kCapture)]: false,
//                                                                                                                         [Symbol(async_id_symbol)]: 24,
//                                                                                                                             [Symbol(http.server.connections)]: ConnectionsList { },
//             [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
//                 _idleTimeout: 30000,
//                     _idlePrev: [TimersList],
//                         _idleNext: [TimersList],
//                             _idleStart: 1245,
//                                 _onTimeout: [Function: bound checkConnections],
//                                     _timerArgs: undefined,
//                                         _repeat: 30000,
//                                             _destroyed: false,
//                                                 [Symbol(refed)]: false,
//                                                     [Symbol(kHasPrimitive)]: false,
//                                                         [Symbol(asyncId)]: 23,
//                                                             [Symbol(triggerId)]: 1
//             },
//             [Symbol(kUniqueHeaders)]: null
//         },
//         _server: Server {
//             maxHeaderSize: undefined,
//                 insecureHTTPParser: undefined,
//                     requestTimeout: 300000,
//                         headersTimeout: 60000,
//                             keepAliveTimeout: 5000,
//                                 connectionsCheckingInterval: 30000,
//                                     _events: [Object: null prototype],
//                                         _eventsCount: 2,
//                                             _maxListeners: undefined,
//                                                 _connections: 1,
//                                                     _handle: [TCP],
//                                                         _usingWorkers: false,
//                                                             _workers: [],
//                                                                 _unref: false,
//                                                                     allowHalfOpen: true,
//                                                                         pauseOnConnect: false,
//                                                                             noDelay: true,
//                                                                                 keepAlive: false,
//                                                                                     keepAliveInitialDelay: 0,
//                                                                                         httpAllowHalfOpen: false,
//                                                                                             timeout: 0,
//                                                                                                 maxHeadersCount: null,
//                                                                                                     maxRequestsPerSocket: 0,
//                                                                                                         _connectionKey: '6::::3000',
//                                                                                                             [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//                                                                                                                 [Symbol(ServerResponse)]: [Function: ServerResponse],
//                                                                                                                     [Symbol(kCapture)]: false,
//                                                                                                                         [Symbol(async_id_symbol)]: 24,
//                                                                                                                             [Symbol(http.server.connections)]: ConnectionsList { },
//             [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
//                 _idleTimeout: 30000,
//                     _idlePrev: [TimersList],
//                         _idleNext: [TimersList],
//                             _idleStart: 1245,
//                                 _onTimeout: [Function: bound checkConnections],
//                                     _timerArgs: undefined,
//                                         _repeat: 30000,
//                                             _destroyed: false,
//                                                 [Symbol(refed)]: false,
//                                                     [Symbol(kHasPrimitive)]: false,
//                                                         [Symbol(asyncId)]: 23,
//                                                             [Symbol(triggerId)]: 1
//             },
//             [Symbol(kUniqueHeaders)]: null
//         },
//         parser: HTTPParser {
//             '0': null,
//                 '1': [Function: parserOnHeaders],
//                     '2': [Function: parserOnHeadersComplete],
//                         '3': [Function: parserOnBody],
//                             '4': [Function: parserOnMessageComplete],
//                                 '5': [Function: bound onParserExecute],
//                                     '6': [Function: bound onParserTimeout],
//                                         _headers: [],
//                                             _url: '',
//                                                 socket: [Circular * 1],
//                                                     incoming: [Circular * 2],
//                                                         outgoing: null,
//                                                             maxHeaderPairs: 2000,
//                                                                 _consumed: true,
//                                                                     onIncoming: [Function: bound parserOnIncoming],
//                                                                         [Symbol(resource_symbol)]: [HTTPServerAsyncResource]
//         },
//         on: [Function: socketListenerWrap],
//             addListener: [Function: socketListenerWrap],
//                 prependListener: [Function: socketListenerWrap],
//                     setEncoding: [Function: socketSetEncoding],
//                         _paused: false,
//                             _httpMessage: ServerResponse {
//             _events: [Object: null prototype],
//                 _eventsCount: 1,
//                     _maxListeners: undefined,
//                         outputData: [],
//                             outputSize: 0,
//                                 writable: true,
//                                     destroyed: false,
//                                         _last: false,
//                                             chunkedEncoding: false,
//                                                 shouldKeepAlive: true,
//                                                     maxRequestsOnConnectionReached: false,
//                                                         _defaultKeepAlive: true,
//                                                             useChunkedEncodingByDefault: true,
//                                                                 sendDate: true,
//                                                                     _removedConnection: false,
//                                                                         _removedContLen: false,
//                                                                             _removedTE: false,
//                                                                                 strictContentLength: false,
//                                                                                     _contentLength: null,
//                                                                                         _hasBody: true,
//                                                                                             _trailer: '',
//                                                                                                 finished: false,
//                                                                                                     _headerSent: false,
//                                                                                                         _closed: false,
//                                                                                                             socket: [Circular * 1],
//                                                                                                                 _header: null,
//                                                                                                                     _keepAliveTimeout: 5000,
//                                                                                                                         _onPendingData: [Function: bound updateOutgoingData],
//                                                                                                                             req: [Circular * 2],
//                                                                                                                                 _sent100: false,
//                                                                                                                                     _expect_continue: false,
//                                                                                                                                         _maxRequestsPerSocket: 0,
//                                                                                                                                             locals: [Object: null prototype] { },
//             writeHead: [Function: writeHead],
//                 [Symbol(kCapture)]: false,
//                     [Symbol(kBytesWritten)]: 0,
//                         [Symbol(kEndCalled)]: false,
//                             [Symbol(kNeedDrain)]: false,
//                                 [Symbol(corked)]: 0,
//                                     [Symbol(kOutHeaders)]: [Object: null prototype],
//                                         [Symbol(kUniqueHeaders)]: null
//         },
//         [Symbol(async_id_symbol)]: 202,
//             [Symbol(kHandle)]: TCP {
//             reading: true,
//                 onconnection: null,
//                     _consumed: true,
//                         [Symbol(owner_symbol)]: [Circular * 1]
//         },
//         [Symbol(lastWriteQueueSize)]: 0,
//             [Symbol(timeout)]: null,
//                 [Symbol(kBuffer)]: null,
//                     [Symbol(kBufferCb)]: null,
//                         [Symbol(kBufferGen)]: null,
//                             [Symbol(kCapture)]: false,
//                                 [Symbol(kSetNoDelay)]: true,
//                                     [Symbol(kSetKeepAlive)]: false,
//                                         [Symbol(kSetKeepAliveInitialDelay)]: 0,
//                                             [Symbol(kBytesRead)]: 0,
//                                                 [Symbol(kBytesWritten)]: 0
//     },
//     httpVersionMajor: 1,
//         httpVersionMinor: 1,
//             httpVersion: '1.1',
//                 complete: true,
//                     rawHeaders: [
//                         'Host',
//                         'localhost:3000',
//                         'Connection',
//                         'keep-alive',
//                         'Upgrade-Insecure-Requests',
//                         '1',
//                         'User-Agent',
//                         'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36',
//                         'Accept',
//                         'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
//                         'Sec-Fetch-Site',
//                         'cross-site',
//                         'Sec-Fetch-Mode',
//                         'navigate',
//                         'Sec-Fetch-User',
//                         '?1',
//                         'Sec-Fetch-Dest',
//                         'document',
//                         'sec-ch-ua',
//                         '"Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"',
//                         'sec-ch-ua-mobile',
//                         '?0',
//                         'sec-ch-ua-platform',
//                         '"Windows"',
//                         'Accept-Encoding',
//                         'gzip, deflate, br',
//                         'Accept-Language',
//                         'en-EG,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6',
//                         'Cookie',
//                         'tuto-session=eyJwYXNzcG9ydCI6eyJ1c2VyIjp7InByb3ZpZGVyIjoiZ29vZ2xlIiwic3ViIjoiMTEyMjI4OTkyNjgzNDgzNTY2ODc4IiwiaWQiOiIxMTIyMjg5OTI2ODM0ODM1NjY4NzgiLCJkaXNwbGF5TmFtZSI6Imdlb3JnZSBheW1hbiIsIm5hbWUiOnsiZ2l2ZW5OYW1lIjoiZ2VvcmdlIiwiZmFtaWx5TmFtZSI6ImF5bWFuIn0sImdpdmVuX25hbWUiOiJnZW9yZ2UiLCJmYW1pbHlfbmFtZSI6ImF5bWFuIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInZlcmlmaWVkIjp0cnVlLCJsYW5ndWFnZSI6ImVuLUdCIiwiZW1haWwiOiJnb3JnZWFiYWRpZXJAZ21haWwuY29tIiwiZW1haWxzIjpbeyJ2YWx1ZSI6ImdvcmdlYWJhZGllckBnbWFpbC5jb20iLCJ0eXBlIjoiYWNjb3VudCJ9XSwicGhvdG9zIjpbeyJ2YWx1ZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FFZEZUcDdQejNaUUQxSDd6WDJqNWRxMjJQaDBpaDFrX2ZKVDF2ajQ2eVZHMmc9czk2LWMiLCJ0eXBlIjoiZGVmYXVsdCJ9XSwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FFZEZUcDdQejNaUUQxSDd6WDJqNWRxMjJQaDBpaDFrX2ZKVDF2ajQ2eVZHMmc9czk2LWMiLCJfcmF3Ijoie1xuICBcInN1YlwiOiBcIjExMjIyODk5MjY4MzQ4MzU2Njg3OFwiLFxuICBcIm5hbWVcIjogXCJnZW9yZ2UgYXltYW5cIixcbiAgXCJnaXZlbl9uYW1lXCI6IFwiZ2VvcmdlXCIsXG4gIFwiZmFtaWx5X25hbWVcIjogXCJheW1hblwiLFxuICBcInBpY3R1cmVcIjogXCJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BRWRGVHA3UHozWlFEMUg3elgyajVkcTIyUGgwaWgxa19mSlQxdmo0NnlWRzJnXFx1MDAzZHM5Ni1jXCIsXG4gIFwiZW1haWxcIjogXCJnb3JnZWFiYWRpZXJAZ21haWwuY29tXCIsXG4gIFwiZW1haWxfdmVyaWZpZWRcIjogdHJ1ZSxcbiAgXCJsb2NhbGVcIjogXCJlbi1HQlwiXG59IiwiX2pzb24iOnsic3ViIjoiMTEyMjI4OTkyNjgzNDgzNTY2ODc4IiwibmFtZSI6Imdlb3JnZSBheW1hbiIsImdpdmVuX25hbWUiOiJnZW9yZ2UiLCJmYW1pbHlfbmFtZSI6ImF5bWFuIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FFZEZUcDdQejNaUUQxSDd6WDJqNWRxMjJQaDBpaDFrX2ZKVDF2ajQ2eVZHMmc9czk2LWMiLCJlbWFpbCI6ImdvcmdlYWJhZGllckBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibG9jYWxlIjoiZW4tR0IifX19fQ==; tuto-session.sig=C2S_HAjZfh9a48JFRG2QGP7PKp4'
//                     ],
//                         rawTrailers: [],
//                             aborted: false,
//                                 upgrade: false,
//                                     url: '/lavia/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2I2MjkzZmVhMTQzY2UwYzIwMWNjMTEiLCJpYXQiOjE2NzI4ODI0OTUsImV4cCI6MTY3Mjg4MzA5NX0.v_KBhezH6bVUNUZam_IvmydhuKLKEQLrOLBkuOdA_qY',
//                                         method: 'GET',
//                                             statusCode: null,
//                                                 statusMessage: null,
//                                                     client: <ref * 1 > Socket {
//         connecting: false,
//             _hadError: false,
//                 _parent: null,
//                     _host: null,
//                         _closeAfterHandlingError: false,
//                             _readableState: ReadableState {
//             objectMode: false,
//                 highWaterMark: 16384,
//                     buffer: BufferList { head: null, tail: null, length: 0 },
//             length: 0,
//                 pipes: [],
//                     flowing: true,
//                         ended: false,
//                             endEmitted: false,
//                                 reading: true,
//                                     constructed: true,
//                                         sync: false,
//                                             needReadable: true,
//                                                 emittedReadable: false,
//                                                     readableListening: false,
//                                                         resumeScheduled: false,
//                                                             errorEmitted: false,
//                                                                 emitClose: false,
//                                                                     autoDestroy: true,
//                                                                         destroyed: false,
//                                                                             errored: null,
//                                                                                 closed: false,
//                                                                                     closeEmitted: false,
//                                                                                         defaultEncoding: 'utf8',
//                                                                                             awaitDrainWriters: null,
//                                                                                                 multiAwaitDrain: false,
//                                                                                                     readingMore: false,
//                                                                                                         dataEmitted: false,
//                                                                                                             decoder: null,
//                                                                                                                 encoding: null,
//                                                                                                                     [Symbol(kPaused)]: false
//         },
//         _events: [Object: null prototype] {
//             end: [Array],
//                 timeout: [Function: socketOnTimeout],
//                     data: [Function: bound socketOnData],
//                         error: [Function: socketOnError],
//                             close: [Array],
//                                 drain: [Function: bound socketOnDrain],
//                                     resume: [Function: onSocketResume],
//                                         pause: [Function: onSocketPause]
//         },
//         _eventsCount: 8,
//             _maxListeners: undefined,
//                 _writableState: WritableState {
//             objectMode: false,
//                 highWaterMark: 16384,
//                     finalCalled: false,
//                         needDrain: false,
//                             ending: false,
//                                 ended: false,
//                                     finished: false,
//                                         destroyed: false,
//                                             decodeStrings: false,
//                                                 defaultEncoding: 'utf8',
//                                                     length: 0,
//                                                         writing: false,
//                                                             corked: 0,
//                                                                 sync: true,
//                                                                     bufferProcessing: false,
//                                                                         onwrite: [Function: bound onwrite],
//                                                                             writecb: null,
//                                                                                 writelen: 0,
//                                                                                     afterWriteTickInfo: null,
//                                                                                         buffered: [],
//                                                                                             bufferedIndex: 0,
//                                                                                                 allBuffers: true,
//                                                                                                     allNoop: true,
//                                                                                                         pendingcb: 0,
//                                                                                                             constructed: true,
//                                                                                                                 prefinished: false,
//                                                                                                                     errorEmitted: false,
//                                                                                                                         emitClose: false,
//                                                                                                                             autoDestroy: true,
//                                                                                                                                 errored: null,
//                                                                                                                                     closed: false,
//                                                                                                                                         closeEmitted: false,
//                                                                                                                                             [Symbol(kOnFinished)]: []
//         },
//         allowHalfOpen: true,
//             _sockname: null,
//                 _pendingData: null,
//                     _pendingEncoding: '',
//                         server: Server {
//             maxHeaderSize: undefined,
//                 insecureHTTPParser: undefined,
//                     requestTimeout: 300000,
//                         headersTimeout: 60000,
//                             keepAliveTimeout: 5000,
//                                 connectionsCheckingInterval: 30000,
//                                     _events: [Object: null prototype],
//                                         _eventsCount: 2,
//                                             _maxListeners: undefined,
//                                                 _connections: 1,
//                                                     _handle: [TCP],
//                                                         _usingWorkers: false,
//                                                             _workers: [],
//                                                                 _unref: false,
//                                                                     allowHalfOpen: true,
//                                                                         pauseOnConnect: false,
//                                                                             noDelay: true,
//                                                                                 keepAlive: false,
//                                                                                     keepAliveInitialDelay: 0,
//                                                                                         httpAllowHalfOpen: false,
//                                                                                             timeout: 0,
//                                                                                                 maxHeadersCount: null,
//                                                                                                     maxRequestsPerSocket: 0,
//                                                                                                         _connectionKey: '6::::3000',
//                                                                                                             [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//                                                                                                                 [Symbol(ServerResponse)]: [Function: ServerResponse],
//                                                                                                                     [Symbol(kCapture)]: false,
//                                                                                                                         [Symbol(async_id_symbol)]: 24,
//                                                                                                                             [Symbol(http.server.connections)]: ConnectionsList { },
//             [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
//                 _idleTimeout: 30000,
//                     _idlePrev: [TimersList],
//                         _idleNext: [TimersList],
//                             _idleStart: 1245,
//                                 _onTimeout: [Function: bound checkConnections],
//                                     _timerArgs: undefined,
//                                         _repeat: 30000,
//                                             _destroyed: false,
//                                                 [Symbol(refed)]: false,
//                                                     [Symbol(kHasPrimitive)]: false,
//                                                         [Symbol(asyncId)]: 23,
//                                                             [Symbol(triggerId)]: 1
//             },
//             [Symbol(kUniqueHeaders)]: null
//         },
//         _server: Server {
//             maxHeaderSize: undefined,
//                 insecureHTTPParser: undefined,
//                     requestTimeout: 300000,
//                         headersTimeout: 60000,
//                             keepAliveTimeout: 5000,
//                                 connectionsCheckingInterval: 30000,
//                                     _events: [Object: null prototype],
//                                         _eventsCount: 2,
//                                             _maxListeners: undefined,
//                                                 _connections: 1,
//                                                     _handle: [TCP],
//                                                         _usingWorkers: false,
//                                                             _workers: [],
//                                                                 _unref: false,
//                                                                     allowHalfOpen: true,
//                                                                         pauseOnConnect: false,
//                                                                             noDelay: true,
//                                                                                 keepAlive: false,
//                                                                                     keepAliveInitialDelay: 0,
//                                                                                         httpAllowHalfOpen: false,
//                                                                                             timeout: 0,
//                                                                                                 maxHeadersCount: null,
//                                                                                                     maxRequestsPerSocket: 0,
//                                                                                                         _connectionKey: '6::::3000',
//                                                                                                             [Symbol(IncomingMessage)]: [Function: IncomingMessage],
//                                                                                                                 [Symbol(ServerResponse)]: [Function: ServerResponse],
//                                                                                                                     [Symbol(kCapture)]: false,
//                                                                                                                         [Symbol(async_id_symbol)]: 24,
//                                                                                                                             [Symbol(http.server.connections)]: ConnectionsList { },
//             [Symbol(http.server.connectionsCheckingInterval)]: Timeout {
//                 _idleTimeout: 30000,
//                     _idlePrev: [TimersList],
//                         _idleNext: [TimersList],
//                             _idleStart: 1245,
//                                 _onTimeout: [Function: bound checkConnections],
//                                     _timerArgs: undefined,
//                                         _repeat: 30000,
//                                             _destroyed: false,
//                                                 [Symbol(refed)]: false,
//                                                     [Symbol(kHasPrimitive)]: false,
//                                                         [Symbol(asyncId)]: 23,
//                                                             [Symbol(triggerId)]: 1
//             },
//             [Symbol(kUniqueHeaders)]: null
//         },
//         parser: HTTPParser {
//             '0': null,
//                 '1': [Function: parserOnHeaders],
//                     '2': [Function: parserOnHeadersComplete],
//                         '3': [Function: parserOnBody],
//                             '4': [Function: parserOnMessageComplete],
//                                 '5': [Function: bound onParserExecute],
//                                     '6': [Function: bound onParserTimeout],
//                                         _headers: [],
//                                             _url: '',
//                                                 socket: [Circular * 1],
//                                                     incoming: [Circular * 2],
//                                                         outgoing: null,
//                                                             maxHeaderPairs: 2000,
//                                                                 _consumed: true,
//                                                                     onIncoming: [Function: bound parserOnIncoming],
//                                                                         [Symbol(resource_symbol)]: [HTTPServerAsyncResource]
//         },
//         on: [Function: socketListenerWrap],
//             addListener: [Function: socketListenerWrap],
//                 prependListener: [Function: socketListenerWrap],
//                     setEncoding: [Function: socketSetEncoding],
//                         _paused: false,
//                             _httpMessage: ServerResponse {
//             _events: [Object: null prototype],
//                 _eventsCount: 1,
//                     _maxListeners: undefined,
//                         outputData: [],
//                             outputSize: 0,
//                                 writable: true,
//                                     destroyed: false,
//                                         _last: false,
//                                             chunkedEncoding: false,
//                                                 shouldKeepAlive: true,
//                                                     maxRequestsOnConnectionReached: false,
//                                                         _defaultKeepAlive: true,
//                                                             useChunkedEncodingByDefault: true,
//                                                                 sendDate: true,
//                                                                     _removedConnection: false,
//                                                                         _removedContLen: false,
//                                                                             _removedTE: false,
//                                                                                 strictContentLength: false,
//                                                                                     _contentLength: null,
//                                                                                         _hasBody: true,
//                                                                                             _trailer: '',
//                                                                                                 finished: false,
//                                                                                                     _headerSent: false,
//                                                                                                         _closed: false,
//                                                                                                             socket: [Circular * 1],
//                                                                                                                 _header: null,
//                                                                                                                     _keepAliveTimeout: 5000,
//                                                                                                                         _onPendingData: [Function: bound updateOutgoingData],
//                                                                                                                             req: [Circular * 2],
//                                                                                                                                 _sent100: false,
//                                                                                                                                     _expect_continue: false,
//                                                                                                                                         _maxRequestsPerSocket: 0,
//                                                                                                                                             locals: [Object: null prototype] { },
//             writeHead: [Function: writeHead],
//                 [Symbol(kCapture)]: false,
//                     [Symbol(kBytesWritten)]: 0,
//                         [Symbol(kEndCalled)]: false,
//                             [Symbol(kNeedDrain)]: false,
//                                 [Symbol(corked)]: 0,
//                                     [Symbol(kOutHeaders)]: [Object: null prototype],
//                                         [Symbol(kUniqueHeaders)]: null
//         },
//         [Symbol(async_id_symbol)]: 202,
//             [Symbol(kHandle)]: TCP {
//             reading: true,
//                 onconnection: null,
//                     _consumed: true,
//                         [Symbol(owner_symbol)]: [Circular * 1]
//         },
//         [Symbol(lastWriteQueueSize)]: 0,
//             [Symbol(timeout)]: null,
//                 [Symbol(kBuffer)]: null,
//                     [Symbol(kBufferCb)]: null,
//                         [Symbol(kBufferGen)]: null,
//                             [Symbol(kCapture)]: false,
//                                 [Symbol(kSetNoDelay)]: true,
//                                     [Symbol(kSetKeepAlive)]: false,
//                                         [Symbol(kSetKeepAliveInitialDelay)]: 0,
//                                             [Symbol(kBytesRead)]: 0,
//                                                 [Symbol(kBytesWritten)]: 0
//     },
//     _consuming: false,
//         _dumped: false,
//             next: [Function: next],
//                 baseUrl: '',
//                     originalUrl: '/lavia/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2I2MjkzZmVhMTQzY2UwYzIwMWNjMTEiLCJpYXQiOjE2NzI4ODI0OTUsImV4cCI6MTY3Mjg4MzA5NX0.v_KBhezH6bVUNUZam_IvmydhuKLKEQLrOLBkuOdA_qY',
//                         _parsedUrl: Url {
//         protocol: null,
//             slashes: null,
//                 auth: null,
//                     host: null,
//                         port: null,
//                             hostname: null,
//                                 hash: null,
//                                     search: null,
//                                         query: null,
//                                             pathname: '/lavia/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2I2MjkzZmVhMTQzY2UwYzIwMWNjMTEiLCJpYXQiOjE2NzI4ODI0OTUsImV4cCI6MTY3Mjg4MzA5NX0.v_KBhezH6bVUNUZam_IvmydhuKLKEQLrOLBkuOdA_qY',
//                                                 path: '/lavia/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2I2MjkzZmVhMTQzY2UwYzIwMWNjMTEiLCJpYXQiOjE2NzI4ODI0OTUsImV4cCI6MTY3Mjg4MzA5NX0.v_KBhezH6bVUNUZam_IvmydhuKLKEQLrOLBkuOdA_qY',
//                                                     href: '/lavia/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2I2MjkzZmVhMTQzY2UwYzIwMWNjMTEiLCJpYXQiOjE2NzI4ODI0OTUsImV4cCI6MTY3Mjg4MzA5NX0.v_KBhezH6bVUNUZam_IvmydhuKLKEQLrOLBkuOdA_qY',
//                                                         _raw: '/lavia/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2I2MjkzZmVhMTQzY2UwYzIwMWNjMTEiLCJpYXQiOjE2NzI4ODI0OTUsImV4cCI6MTY3Mjg4MzA5NX0.v_KBhezH6bVUNUZam_IvmydhuKLKEQLrOLBkuOdA_qY'
//     },
//     params: {
//         confimation: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2I2MjkzZmVhMTQzY2UwYzIwMWNjMTEiLCJpYXQiOjE2NzI4ODI0OTUsImV4cCI6MTY3Mjg4MzA5NX0.v_KBhezH6bVUNUZam_IvmydhuKLKEQLrOLBkuOdA_qY'
//     },
//     query: { },
//     res: <ref * 3 > ServerResponse {
//         _events: [Object: null prototype] { finish: [Function: bound resOnFinish] },
//         _eventsCount: 1,
//             _maxListeners: undefined,
//                 outputData: [],
//                     outputSize: 0,
//                         writable: true,
//                             destroyed: false,
//                                 _last: false,
//                                     chunkedEncoding: false,
//                                         shouldKeepAlive: true,
//                                             maxRequestsOnConnectionReached: false,
//                                                 _defaultKeepAlive: true,
//                                                     useChunkedEncodingByDefault: true,
//                                                         sendDate: true,
//                                                             _removedConnection: false,
//                                                                 _removedContLen: false,
//                                                                     _removedTE: false,
//                                                                         strictContentLength: false,
//                                                                             _contentLength: null,
//                                                                                 _hasBody: true,
//                                                                                     _trailer: '',
//                                                                                         finished: false,
//                                                                                             _headerSent: false,
//                                                                                                 _closed: false,
//                                                                                                     socket: <ref * 1 > Socket {
//             connecting: false,
//                 _hadError: false,
//                     _parent: null,
//                         _host: null,
//                             _closeAfterHandlingError: false,
//                                 _readableState: [ReadableState],
//                                     _events: [Object: null prototype],
//                                         _eventsCount: 8,
//                                             _maxListeners: undefined,
//                                                 _writableState: [WritableState],
//                                                     allowHalfOpen: true,
//                                                         _sockname: null,
//                                                             _pendingData: null,
//                                                                 _pendingEncoding: '',
//                                                                     server: [Server],
//                                                                         _server: [Server],
//                                                                             parser: [HTTPParser],
//                                                                                 on: [Function: socketListenerWrap],
//                                                                                     addListener: [Function: socketListenerWrap],
//                                                                                         prependListener: [Function: socketListenerWrap],
//                                                                                             setEncoding: [Function: socketSetEncoding],
//                                                                                                 _paused: false,
//                                                                                                     _httpMessage: [Circular * 3],
//                                                                                                         [Symbol(async_id_symbol)]: 202,
//                                                                                                             [Symbol(kHandle)]: [TCP],
//                                                                                                                 [Symbol(lastWriteQueueSize)]: 0,
//                                                                                                                     [Symbol(timeout)]: null,
//                                                                                                                         [Symbol(kBuffer)]: null,
//                                                                                                                             [Symbol(kBufferCb)]: null,
//                                                                                                                                 [Symbol(kBufferGen)]: null,
//                                                                                                                                     [Symbol(kCapture)]: false,
//                                                                                                                                         [Symbol(kSetNoDelay)]: true,
//                                                                                                                                             [Symbol(kSetKeepAlive)]: false,
//                                                                                                                                                 [Symbol(kSetKeepAliveInitialDelay)]: 0,
//                                                                                                                                                     [Symbol(kBytesRead)]: 0,
//                                                                                                                                                         [Symbol(kBytesWritten)]: 0
//         },
//         _header: null,
//             _keepAliveTimeout: 5000,
//                 _onPendingData: [Function: bound updateOutgoingData],
//                     req: [Circular * 2],
//                         _sent100: false,
//                             _expect_continue: false,
//                                 _maxRequestsPerSocket: 0,
//                                     locals: [Object: null prototype] { },
//         writeHead: [Function: writeHead],
//             [Symbol(kCapture)]: false,
//                 [Symbol(kBytesWritten)]: 0,
//                     [Symbol(kEndCalled)]: false,
//                         [Symbol(kNeedDrain)]: false,
//                             [Symbol(corked)]: 0,
//                                 [Symbol(kOutHeaders)]: [Object: null prototype] { 'x-powered-by': [Array] },
//         [Symbol(kUniqueHeaders)]: null
//     },
//     sessionOptions: { },
//     session: [Getter / Setter],
//         logIn: [Function(anonymous)],
//             login: [Function(anonymous)],
//                 logOut: [Function(anonymous)],
//                     logout: [Function(anonymous)],
//                         isAuthenticated: [Function(anonymous)],
//                             isUnauthenticated: [Function(anonymous)],
//                                 _sessionManager: SessionManager {
//         _key: 'passport',
//             _serializeUser: [Function: bound]
//     },
//     _passport: {
//         instance: Authenticator {
//             _key: 'passport',
//                 _strategies: [Object],
//                     _serializers: [Array],
//                         _deserializers: [Array],
//                             _infoTransformers: [],
//                                 _framework: [Object],
//                                     _sm: [SessionManager],
//                                         Authenticator: [Function: Authenticator],
//                                             Passport: [Function: Authenticator],
//                                                 Strategy: [Function],
//                                                     strategies: [Object],
//                                                         _userProperty: 'user'
//         }
//     },
//     user: {
//         _id: new ObjectId("63b6293fea143ce0c201cc11"),
//             userName: 'george ayman',
//                 role: new ObjectId("63b35526685484a36b4889c2"),
//                     email: 'gorgeabadier@gmail.com',
//                         status: true,
//                             date: null,
//                                 password: '$2a$10$.ia2JBiqeDUh.26adDrDn.uj.gvdA.fRs9aPu4r9Z8/IeL1XGJAtW',
//                                     liked: [],
//                                         points: 0,
//                                             phoneNums: [],
//                                                 chats: [],
//                                                     quizzes: [],
//                                                         notifications: [],
//                                                             __v: 0
//     },
//     body: { },
//     route: Route {
//         path: '/lavia/confirm/:confimation',
//             stack: [[Layer], [Layer], [Layer]],
//                 methods: { get: true }
//     },
//     token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2I2MjkzZmVhMTQzY2UwYzIwMWNjMTEiLCJpYXQiOjE2NzI4ODI0OTUsImV4cCI6MTY3Mjg4MzA5NX0.v_KBhezH6bVUNUZam_IvmydhuKLKEQLrOLBkuOdA_qY',
//         [Symbol(kCapture)]: false,
//             [Symbol(kHeaders)]: {
//         host: 'localhost:3000',
//             connection: 'keep-alive',
//                 'upgrade-insecure-requests': '1',
//                     'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36',
//                         accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
//                             'sec-fetch-site': 'cross-site',
//                                 'sec-fetch-mode': 'navigate',
//                                     'sec-fetch-user': '?1',
//                                         'sec-fetch-dest': 'document',
//                                             'sec-ch-ua': '"Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"',
//                                                 'sec-ch-ua-mobile': '?0',
//                                                     'sec-ch-ua-platform': '"Windows"',
//                                                         'accept-encoding': 'gzip, deflate, br',
//                                                             'accept-language': 'en-EG,en;q=0.9,ar-EG;q=0.8,ar;q=0.7,en-US;q=0.6',
//                                                                 cookie: 'tuto-session=eyJwYXNzcG9ydCI6eyJ1c2VyIjp7InByb3ZpZGVyIjoiZ29vZ2xlIiwic3ViIjoiMTEyMjI4OTkyNjgzNDgzNTY2ODc4IiwiaWQiOiIxMTIyMjg5OTI2ODM0ODM1NjY4NzgiLCJkaXNwbGF5TmFtZSI6Imdlb3JnZSBheW1hbiIsIm5hbWUiOnsiZ2l2ZW5OYW1lIjoiZ2VvcmdlIiwiZmFtaWx5TmFtZSI6ImF5bWFuIn0sImdpdmVuX25hbWUiOiJnZW9yZ2UiLCJmYW1pbHlfbmFtZSI6ImF5bWFuIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInZlcmlmaWVkIjp0cnVlLCJsYW5ndWFnZSI6ImVuLUdCIiwiZW1haWwiOiJnb3JnZWFiYWRpZXJAZ21haWwuY29tIiwiZW1haWxzIjpbeyJ2YWx1ZSI6ImdvcmdlYWJhZGllckBnbWFpbC5jb20iLCJ0eXBlIjoiYWNjb3VudCJ9XSwicGhvdG9zIjpbeyJ2YWx1ZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FFZEZUcDdQejNaUUQxSDd6WDJqNWRxMjJQaDBpaDFrX2ZKVDF2ajQ2eVZHMmc9czk2LWMiLCJ0eXBlIjoiZGVmYXVsdCJ9XSwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FFZEZUcDdQejNaUUQxSDd6WDJqNWRxMjJQaDBpaDFrX2ZKVDF2ajQ2eVZHMmc9czk2LWMiLCJfcmF3Ijoie1xuICBcInN1YlwiOiBcIjExMjIyODk5MjY4MzQ4MzU2Njg3OFwiLFxuICBcIm5hbWVcIjogXCJnZW9yZ2UgYXltYW5cIixcbiAgXCJnaXZlbl9uYW1lXCI6IFwiZ2VvcmdlXCIsXG4gIFwiZmFtaWx5X25hbWVcIjogXCJheW1hblwiLFxuICBcInBpY3R1cmVcIjogXCJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BRWRGVHA3UHozWlFEMUg3elgyajVkcTIyUGgwaWgxa19mSlQxdmo0NnlWRzJnXFx1MDAzZHM5Ni1jXCIsXG4gIFwiZW1haWxcIjogXCJnb3JnZWFiYWRpZXJAZ21haWwuY29tXCIsXG4gIFwiZW1haWxfdmVyaWZpZWRcIjogdHJ1ZSxcbiAgXCJsb2NhbGVcIjogXCJlbi1HQlwiXG59IiwiX2pzb24iOnsic3ViIjoiMTEyMjI4OTkyNjgzNDgzNTY2ODc4IiwibmFtZSI6Imdlb3JnZSBheW1hbiIsImdpdmVuX25hbWUiOiJnZW9yZ2UiLCJmYW1pbHlfbmFtZSI6ImF5bWFuIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FFZEZUcDdQejNaUUQxSDd6WDJqNWRxMjJQaDBpaDFrX2ZKVDF2ajQ2eVZHMmc9czk2LWMiLCJlbWFpbCI6ImdvcmdlYWJhZGllckBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibG9jYWxlIjoiZW4tR0IifX19fQ==; tuto-session.sig=C2S_HAjZfh9a48JFRG2QGP7PKp4'
//     },
//     [Symbol(kHeadersCount)]: 30,
//         [Symbol(kTrailers)]: null,
//             [Symbol(kTrailersCount)]: 0
// }